version: '3'
services:
  client:
    build: .
    # ports:
      # - 3002:80

  swag:
    image: lscr.io/linuxserver/swag
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Denver
      - URL=wightman.duckdns.org
      - VALIDATION=duckdns
      - DUCKDNSTOKEN=${DUCKDNSTOKEN}
      - STAGING=false 
    volumes:
      - /home/caleb/data/swag:/config
      - ./swag-default.conf:/config/nginx/site-confs/default.conf
    ports:
    - 0.0.0.0:3002:443
    restart: unless-stopped

  api:
    image: cwighty/storageapi
    volumes:
      - /home/caleb/data/api_data:/app/data # Mount a volume for data persistence
