name: deploy my site

env:
  DUCKDNSTOKEN: ${{ secrets.DUCKDNSTOKEN }}

on: [push, workflow_dispatch]

jobs:
  lint:
    runs-on: [self-hosted]
    steps:
      - name: checkout repo
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Run ESLint
        run: npx eslint --ext js,jsx,tsx,ts src

  deploy-application:
    needs: lint
    runs-on: [self-hosted]
    steps:
      - name: checkout repo
        uses: actions/checkout@v2

      - name: redeploy application
        run: |
          docker compose pull
          docker compose build
          docker compose up -d
